// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZuzDygWtHBxNOYjnjQwj8apkGjvPFwgc',
    appId: '1:256747937217:web:329370d627d4b3b4e2e340',
    messagingSenderId: '256747937217',
    projectId: 'mapmate-2026',
    authDomain: 'mapmate-2026.firebaseapp.com',
    storageBucket: 'mapmate-2026.firebasestorage.app',
    measurementId: 'G-HY0WLLWC39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1tnkzWR4WjMvFciAD4bpDHk_UwGB-F5I',
    appId: '1:256747937217:android:d90df3dd45879a24e2e340',
    messagingSenderId: '256747937217',
    projectId: 'mapmate-2026',
    storageBucket: 'mapmate-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaz5r-c_vH3SQo6SGkEydLFIobmtpVIXQ',
    appId: '1:256747937217:ios:1136f43f4aec22cfe2e340',
    messagingSenderId: '256747937217',
    projectId: 'mapmate-2026',
    storageBucket: 'mapmate-2026.firebasestorage.app',
    iosBundleId: 'com.example.mapmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaz5r-c_vH3SQo6SGkEydLFIobmtpVIXQ',
    appId: '1:256747937217:ios:1136f43f4aec22cfe2e340',
    messagingSenderId: '256747937217',
    projectId: 'mapmate-2026',
    storageBucket: 'mapmate-2026.firebasestorage.app',
    iosBundleId: 'com.example.mapmate',
  );
}
